name: Deploy to S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4  # v3에서 v4로 업데이트

      - name: Setup Node.js
        uses: actions/setup-node@v4  # v3에서 v4로 업데이트
        with:
          node-version: '20'  # Node.js 버전을 20으로 명시

      - name: Install dependencies
        run: npm ci --legacy-peer-deps  # npm install 대신 ci 사용, peer dependency 충돌 해결

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          NEXT_PUBLIC_AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          NEXT_PUBLIC_KAKAO_MAP_API_KEY: ${{ secrets.NEXT_PUBLIC_KAKAO_MAP_API_KEY }}
          NEXT_PUBLIC_API_BASE_URL: https://c8v9u0g8qg.execute-api.ap-northeast-2.amazonaws.com/prod1

      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Upload to S3
        run: |
          aws s3 sync ./out s3://smwu-food-static --delete
          
      # Cloudfront 캐시 무효화 단계 추가 (환경 변수로 설정)
      - name: Invalidate CloudFront Cache
        if: env.CLOUDFRONT_DISTRIBUTION_ID != ''
        env:
          CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
        run: |
          echo "Invalidating CloudFront cache..."
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        continue-on-error: true
          
      # S3 웹사이트 호스팅 설정 업데이트 (오류 페이지 설정)
      - name: Update S3 Website Configuration
        run: |
          aws s3 website s3://smwu-food-static --index-document index.html --error-document index.html 